import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import path from 'node:path';

test('public duel directory wiring exists in the page shell', async () => {
  const html = await fs.readFile(path.resolve(process.cwd(), 'index.html'), 'utf8');

  assert.match(html, /id="heroActions"/);
  assert.match(html, /id="participantBannerSlot"/);
  assert.match(html, /id="surfaceBackdrop"/);
  assert.match(html, /id="profileDrawer"/);
  assert.match(html, /id="createDrawer"/);
  assert.match(html, /id="manageDrawer"/);
  assert.match(html, /id="browseDrawer"/);
  assert.match(html, /id="miniFantasySection"/);
  assert.match(html, /id="miniFantasyFixtures"/);
  assert.match(html, /id="miniFantasyBuilder"/);
  assert.match(html, /id="miniFantasyLeaderboard"/);
  assert.match(html, /id="miniFantasyLockedViewer"/);
  assert.match(html, /id="miniFantasyPickerModal"/);
  assert.match(html, /id="toastBanner"/);
  assert.match(html, /id="authPanel"/);
  assert.match(html, /id="profilePanel"/);
  assert.match(html, /id="createDuelPanel"/);
  assert.match(html, /id="myDuelsPanel"/);
  assert.match(html, /id="opsPanel"/);
  assert.match(html, /id="duelControlsPanel"/);
  assert.match(html, /id="duelDirectory"/);
  assert.match(html, /id="duelDirectorySummary"/);
  assert.match(html, /id="pickPickerModal"/);
  assert.match(html, /duels-backend\.config\.js/);
  assert.match(html, /duels-backend\.js/);
  assert.match(html, /mini-fantasy\/contest-engine\.js/);
  assert.match(html, /ipl_2026_player_availability\.json/);
  assert.match(html, /function sortedDirectoryDuels\(/);
    assert.match(html, /function buildDuelShareUrl\(/);
    assert.match(html, /function joinDuelByCode\(/);
    assert.match(html, /function copyDuelCode\(/);
    assert.match(html, /function copyInviteMessage\(/);
    assert.match(html, /function visibleDuelLabel\(/);
    assert.match(html, /function renderHeroActions\(/);
  assert.match(html, /function renderParticipantBanner\(/);
  assert.match(html, /function syncSurfaceDrawers\(/);
  assert.match(html, /function renderProfilePanel\(/);
  assert.match(html, /function renderMyDuelsPanel\(/);
  assert.match(html, /function renderOpsPanel\(/);
  assert.match(html, /function readinessPanelHtml\(/);
  assert.match(html, /function renderDuelStudio\(/);
  assert.match(html, /function createCustomDuel\(/);
  assert.match(html, /function claimActiveOpenSlot\(/);
  assert.match(html, /function renderPickPicker\(/);
  assert.match(html, /function deriveCustomBundleLifecycle\(/);
  assert.match(html, /function withFreshLifecycle\(/);
  assert.match(html, /function syncRemoteBundlesForRoom\(/);
  assert.match(html, /function syncMiniFantasyEntries\(/);
  assert.match(html, /function upsertRemoteMiniFantasyEntry\(/);
  assert.match(html, /function loadPlayerAvailabilityData\(/);
  assert.match(html, /function miniFantasyAvailabilityBadgeLabel\(/);
  assert.match(html, /function renderMiniFantasySection\(/);
  assert.match(html, /function renderMiniFantasyFixtures\(/);
  assert.match(html, /function renderMiniFantasyBuilder\(/);
  assert.match(html, /function renderMiniFantasyLeaderboard\(/);
  assert.match(html, /function renderMiniFantasyLockedViewer\(/);
  assert.match(html, /function renderMiniFantasyLastGame\(/);
  assert.match(html, /function renderMiniFantasyPicker\(/);
  assert.match(html, /function saveMiniFantasyEntry\(/);
  assert.match(html, /function usesHostedDuelsBackend\(/);
  assert.match(html, /function initializeDuelsApp\(/);
  assert.match(html, /LOCAL_AUTH_STORAGE_KEY/);
  assert.match(html, /LOCAL_MINI_FANTASY_ENTRIES_STORAGE_KEY/);
  assert.match(html, /data-copy-duel-link=/);
  assert.match(html, /data-pick-key=/);
  assert.match(html, /data-open-picker=/);
  assert.match(html, /data-open-duel=/);
  assert.match(html, /id="joinByCodeForm"/);
  assert.match(html, /id="joinByCodeInput"/);
  assert.match(html, /data-auth-mode="signin"/);
  assert.match(html, /data-auth-mode="signup"/);
  assert.match(html, /Create your account once for both Duels and Mini Fantasy\./);
  assert.match(html, /Only email \+ password are needed here\./);
  assert.match(html, /How Duel works/);
  assert.match(html, /How Mini Fantasy works/);
  assert.match(html, /Fixture-only scoring:/);
  assert.match(html, /Lineup total:/);
  assert.match(html, /scores 30\+ runs or faces 10\+ balls/);
  assert.match(html, /each selected player who appears in the fixture gets <code>\+2<\/code>/);
  assert.match(html, /duck penalty of -5/);
  assert.match(html, /If a fixture ends with no result, every Mini Fantasy player score for that match becomes <code>0<\/code>/);
  assert.match(html, /your captain gets <code>1\.5x<\/code> of every eligible point/);
  assert.match(html, /Missed-lock safety net:/);
  assert.match(html, /Fixture-day visit bonus:/);
  assert.match(html, /New-player catch-up:/);
  assert.match(html, /function upsertRemoteMiniFantasyEntry\([\s\S]*MINI_FANTASY_FORCE_LEADERBOARD_FALLBACK = true;/);
  assert.match(html, /Opens the day before/);
  assert.match(html, /Locks at/);
  assert.match(html, /data-directory-filter=/);
  assert.match(html, /data-mini-fixture=/);
  assert.match(html, /data-mini-pick=/);
  assert.match(html, /data-mini-picker-role=/);
  assert.match(html, /data-mini-picker-value=/);
  assert.match(html, /availability-available/);
  assert.match(html, /availability-doubtful/);
  assert.match(html, /availability-unavailable/);
  assert.match(html, /availability-replaced/);
  assert.match(html, /const savedScroll = scrollEl \? scrollEl\.scrollTop : 0/);
  assert.match(html, /scrollElAfter\) scrollElAfter\.scrollTop = savedScroll/);
  assert.match(html, /window\.history\.replaceState/);
});
